"""Export LightGBM text models to a compact module the bot can import cheaply.

usage: python3 tools/clone_export.py MODELDIR OUT.py
All trees of a model share flat arrays (packed as bytes, loaded with array.frombytes):
  F feature index, T threshold, LC/RC child (>= 0 node, < 0 leaf ~index), V leaf values, R roots.
A nested-tuple literal of the same trees made the judge's compile step fail.
"""
import sys
from array import array
import lightgbm as lgb


def pack(path):
    d = lgb.Booster(model_file=path).dump_model()
    F, T, LC, RC, V, R = array('h'), array('d'), array('i'), array('i'), array('d'), array('i')

    def rec(node):
        if 'leaf_value' in node:
            V.append(node['leaf_value'])
            return ~(len(V) - 1)
        i = len(F)
        F.append(node['split_feature']); T.append(node['threshold']); LC.append(0); RC.append(0)
        LC[i] = rec(node['left_child'])
        RC[i] = rec(node['right_child'])
        return i

    for t in d['tree_info']:
        R.append(rec(t['tree_structure']))
    k = d.get('num_class', 1)
    return k, {n: a for n, a in zip('F T LC RC V R'.split(), (F, T, LC, RC, V, R))}


if __name__ == '__main__':
    md, out = sys.argv[1], sys.argv[2]
    with open(out, 'w') as f:
        f.write('# Generated by tools/clone_export.py from LightGBM models trained on rank-1 replays.\n')
        f.write('from array import array\n\n\ndef _a(code, b):\n    a = array(code)\n    a.frombytes(b)\n    return a\n\n\n')
        import os
        for name in ('kind', 'dir', 'steps'):
            if not os.path.exists('%s/%s.txt' % (md, name)):
                continue
            k, arrs = pack('%s/%s.txt' % (md, name))
            f.write('%s_CLASSES = %d\n' % (name.upper(), k))
            for n, a in arrs.items():
                f.write("%s_%s = _a(%r, %r)\n" % (name.upper(), n, a.typecode, a.tobytes()))
            print(name, 'classes', k, 'trees', len(arrs['R']), 'nodes', len(arrs['F']))
