"""Learn where the rank-1 bot's dragons go in the opening, per map, and write clone/opening.py.

usage: python3 tools/gen_opening.py REPLAY...
For each replay: find the rank-1 side, map its spawn onto the bundled team-0 start (mirror or
180-degree rotation, whichever maps the starts onto each other), and accumulate its head positions
over rounds 10-40. The cells that hold the top half of that mass are the opening targets; the
module stores, per map, the walking distance (portals included) to the nearest target cell in the
team-0 frame, plus the transform for the other side.
"""
import os, sys
from collections import Counter, deque
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(HERE, '..', 'clone'))
from sim import Game
from geom import Geo
import mapdb
import clone_extract as ce

TF = {'mx': lambda x, y, W, H: (W - 1 - x, y), 'rot': lambda x, y, W, H: (W - 1 - x, H - 1 - y)}


def transform(M):
    W, H = M['w'], M['h']
    t0 = {c for t, cs in M['starts'] if t == 0 for c in cs}
    t1 = {c for t, cs in M['starts'] if t == 1 for c in cs}
    for n in ('rot', 'mx'):
        if {TF[n](c % W, c // W, W, H)[1] * W + TF[n](c % W, c // W, W, H)[0] for c in t0} == t1:
            return n
    return None


def main():
    dens = {}
    games = Counter()
    for path in sys.argv[1:]:
        g = Game(path)
        key = ce.bundled(g.info['name'])
        try:
            M = mapdb.load(key)
        except ImportError:
            continue
        W, H = M['w'], M['h']
        T = ce.auto_team(g)
        mine = {y * W + x for t, b in g.info['dragons'] if t == T for x, y in b}
        t0 = {c for t, cs in M['starts'] if t == 0 for c in cs}
        flip = not (mine & t0)
        tf = transform(M)
        d = dens.setdefault(key, Counter())
        games[key] += 1

        def cb(g, e, rnd):
            if e[0] == 'round' and 10 <= rnd <= 40:
                for j, b in g.alive.items():
                    if g.team[j] != T:
                        continue
                    x, y = b[0]
                    if flip:
                        x, y = TF[tf](x, y, W, H)
                    d[y * W + x] += 1
        g.run(cb)
    out = {}
    for key, d in dens.items():
        M = mapdb.load(key); W, H = M['w'], M['h']
        geo_rev = {}
        ctx_nb = []
        for c in range(W * H):
            x, y = c % W, c // W
            wl = M['walls'][c]
            nbs = []
            for k, (dx, dy) in enumerate(((0, -1), (1, 0), (0, 1), (-1, 0))):
                if (wl >> k) & 1:
                    continue
                n = next((dst for cc, dd, dst in M['portals'] if cc == c and dd == k), ((y + dy) % H) * W + (x + dx) % W)
                nbs.append(n)
            for n in nbs:
                geo_rev.setdefault(n, []).append(c)
        total = sum(d.values())
        tgt, acc = set(), 0
        for c, v in d.most_common():
            if acc >= total * 0.5:
                break
            tgt.add(c); acc += v
        dist = [255] * (W * H)
        q = deque()
        for c in tgt:
            dist[c] = 0; q.append(c)
        while q:
            c = q.popleft()
            for p in geo_rev.get(c, ()):
                if dist[p] == 255 and dist[c] < 254:
                    dist[p] = dist[c] + 1; q.append(p)
        out[key] = (transform(M), bytes(dist), len(tgt), games[key])
        print('%-16s games %3d targets %3d transform %s' % (key, games[key], len(tgt), transform(M)))
    with open(os.path.join(HERE, '..', 'clone', 'opening.py'), 'w') as f:
        f.write('# Generated by tools/gen_opening.py: per map (transform, distance to the rank-1 bot\'s\n'
                '# opening positions in the team-0 frame, target cells, replays used).\n')
        f.write('OPEN = {\n')
        for key in sorted(out):
            f.write('    %r: %r,\n' % (key, out[key]))
        f.write('}\n')


if __name__ == '__main__':
    main()
