"""Generate bot/md_<key>.py map modules from the bundled unswbc maps.

Each module holds M = {'w','h','walls','beds','bedtypes','portals','starts'}:
  walls[c]  bits 0-3: kelp on N,E,S,W of cell c; bits 4-7: portal on N,E,S,W
  portals   ((cell, dir, dest_cell), ...)   dir 0..3 = N,E,S,W
  beds[c]   index into bedtypes (0 = no bed); bedtypes[i] = (min_gap, max_gap)
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from geom import Geo

MAPDIR = '/usr/local/lib/python3.11/dist-packages/unswbc/templates/maps'
OUT = os.path.join(os.path.dirname(__file__), '..', 'bot')

def build(path):
    text = open(path).read()
    g = Geo(text)
    W, H = g.W, g.H
    walls = bytearray(W * H)
    portals = []
    for y in range(H):
        for x in range(W):
            c = y * W + x
            for d, ch in enumerate('NESW'):
                ek = g.edge_key(x, y, ch)
                t = g.edges.get(ek, (0, -1))[0]
                if t == 1:
                    walls[c] |= 1 << d
                elif t == 2:
                    walls[c] |= 16 << d
                    dx, dy = g.dest((x, y), ch)
                    portals.append((c, d, dy * W + dx))
    types = [(0, 0)]
    beds = bytearray(W * H)
    for (x, y), mm in g.beds.items():
        if mm not in types: types.append(mm)
        beds[y * W + x] = types.index(mm)
    starts = []
    for l in text.split('\n'):
        p = l.split()
        if p and p[0] == 'DRAGON':
            n = int(p[2]); c = list(map(int, p[3:]))
            starts.append((int(p[1]), tuple(c[2 * i + 1] * W + c[2 * i] for i in range(n))))
    return dict(w=W, h=H, walls=bytes(walls), beds=bytes(beds), bedtypes=tuple(types),
                portals=tuple(portals), starts=tuple(starts))

def main():
    sizes = {}
    for fn in sorted(os.listdir(MAPDIR)):
        if not fn.endswith('.map'): continue
        key = fn[:-4]
        m = build(os.path.join(MAPDIR, fn))
        sizes[key] = (m['w'], m['h'])
        with open(os.path.join(OUT, 'md_%s.py' % key), 'w') as f:
            f.write('# Generated by tools/gen_maps.py from the bundled %s.map\n' % key)
            f.write('M = %r\n' % m)
    with open(os.path.join(OUT, 'mapdb.py'), 'w') as f:
        f.write('# Generated by tools/gen_maps.py: bundled map sizes; md_<key>.py holds each map.\n')
        f.write('SIZES = %r\n\n' % sizes)
        f.write('def load(key):\n    return __import__("md_" + key).M\n')
    print(sizes)

if __name__ == '__main__':
    main()
